all: clean compile run 

compile:
	@gcc -o gtuStudentManagemetSystem gtuStudentManagemetSystem.c

run:
	@./gtuStudentManagemetSystem

clean:
	@rm -f *.o
	clear

cleanlog:
	@echo "" > gtuStudentManagemetSystem.log
